---
- name: Install Nginx
  apt:
    name: nginx
    state: latest




- name:  add user
  group: 
    name: "{{ name }}"
    state: present
- name: Add a group
  user:
    name: "{{ name }}"
    groups: "{{ groups }}"
